### ISSUE TITLE
How do you run the script locally?

### ISSUE THREAD

**Issue by harryworld** [icodeforlove/slack-typeform-inviter#5]
I saw you using `function *($deferred) {}` syntax, is it ES6?

I am now able to run unless I use `babel` to convert it hardly, wonder how to do it in a simple way?

Thanks.

(I'm new to ES6 syntax)

**Comment by icodeforlove** [comment]
you can use `iojs`, `node --harmony`, or `babel` as you mentioned

**Comment by harryworld** [comment]
Oh, just saw it at the bottom of README.

Thanks for answering.
